sudo: true
dist: bionic
language: cpp

git:
    submodules: false

compiler:
    - gcc

os:
    - linux
    
env:
    - BUILD_TYPE=Debug

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:mhier/libboost-latest -y
    - sudo apt-get -qq update
    - sudo apt-get install -y --allow-unauthenticated cmake gcc-8 g++-8 libicu-dev libboost1.70-dev
    - export CXX="g++-8" CC="gcc-8"
    - ${CXX} --version
    - pip install --user cpp-coveralls

install:
    - export CXX="g++-8" CC="gcc-8"
    - ${CXX} --version
    - cmake --version

before_script:
    - mkdir -p build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - cmake --build .
    
script:
    - test/ForumServiceTests/ForumServiceTests
    - test/HttpTests/HttpTests
    - test/MemoryRepositoryBenchmarks/MemoryRepositoryBenchmarks
    
after_success:
    - coveralls -r /home/travis/build/danij/Forum -b /home/travis/build/danij/Forum/build -E .*boost.* -E .*test.* -E .*ForumApp.* --gcov gcov-8 --gcov-options '\-lp'
