sudo: true
dist: trusty
group: deprecated-2017Q4
language: cpp

git:
    submodules: false

compiler:
    - gcc

os:
    - linux
    
env:
    - BUILD_TYPE=Debug

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#    - sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" -y
    - sudo apt-get -qq update
    - sudo apt-get install -y --allow-unauthenticated cmake gcc-6 g++-6 libicu-dev
    - export CXX="g++-6" CC="gcc-6"
    - ${CXX} --version
    - wget https://danistorage.blob.core.windows.net/public/boost1_65.tar.bz2
    - tar -xf boost1_65.tar.bz2
    - pip install --user cpp-coveralls

install:
    - export CXX="g++-6" CC="gcc-6"
    - ${CXX} --version
    - cmake --version

before_script:
    - mkdir -p build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBOOST_ROOT=/home/travis/build/danij/Forum/boost1_65
    - cmake --build .
    
script:
    - test/ForumServiceTests/ForumServiceTests
    - test/MemoryRepositoryBenchmarks/MemoryRepositoryBenchmarks
    
after_success:
    - coveralls -r /home/travis/build/danij/Forum -b /home/travis/build/danij/Forum/build -E .*boost.* -E .*test.* -E .*ForumApp.* --gcov gcov-6 --gcov-options '\-lp'
